language: cpp

matrix:
  include:
    - os: osx
      osx_image: xcode11.2
      env: GCC_VERSION=9
      compiler: g++-9
    - os: osx
      osx_image: xcode10.3
      env: GCC_VERSION=8
      compiler: g++-8

    - os: linux
      dist: bionic
    - os: linux
      dist: xenial
      compiler: g++-7
      addons:
        apt:
          packages:
            - g++-7
          sources:
            - ubuntu-toolchain-r-test
      env:
        - MATRIX_EVAL="CC=gcc-7 CXX=g++-7"

    - os: windows

before_install:
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      brew update
      brew install gcc@${GCC_VERSION} || brew link --overwrite gcc
      brew install lcov
    fi
  - eval "${MATRIX_EVAL}"

install:
  - |
    cd ${TRAVIS_BUILD_DIR}
    mkdir -p build
    cd build
  - |
    if [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      # export CC=${COMPILER_C} CXX=${COMPILER_CXX} PATH=/usr/local/bin:$PATH
      # export CMAKE_OPTIONS="${CMAKE_OPTIONS} -DCMAKE_C_COMPILER=${COMPILER_C} -DCMAKE_CXX_COMPILER=${COMPILER_CXX}"
      if   [[ "${GCC_VERSION}" == "8" ]]; then ln -s /usr/local/Cellar/gcc/8.3.0/bin/gcov-8 /usr/local/bin/gcov;
      elif [[ "${GCC_VERSION}" == "9" ]]; then ln -s /usr/local/Cellar/gcc/9.2.0/bin/gcov-9 /usr/local/bin/gcov;
      fi
    fi
  - cmake ..
  - cmake --build . -j 4

script:
  - ./test_trace